component: scf
name: ap-beijing_default_scf-dns
org: '1256945563'
app: scf-dns
stage: dev
inputs:
  name: scf-dns
  src: ./src
  runtime: Python3.9
  region: ap-beijing
  description: SCF created by Tencent Serverless Toolkit for VS Code
  handler: index.main_handler
  memorySize: 128
  timeout: 3
  events:
    - apigw:
        name: serverless_api
        parameters:
          protocols:
            - http
            - https
          description: The service of Serverless Framework
          environment: release
          endpoints:
            - path: /
              method: GET

# For more information: https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md